# Generated by Django 2.2 on 2020-11-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shap1app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='countrycode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phoneno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
